# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "case_feldm"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "case_feldm"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

snapshots:
  +strategy: timestamp
  +target_schema: snapshots
  +updated_at: uploaded_at

models:
  case_feldm:
    transformed:
      +materialized: view
      schema: transformed
    data_marts:
      +materialized: table
      schema: data_marts
    staging:
      +materialized: view
      schema: staging
    dim_monthly_cohorts:
      +post-hook:
        - "CREATE INDEX IF NOT EXISTS idx_monthlycohorts_cohort_month ON {{ this }} (cohort_month)"
        - "CREATE INDEX IF NOT EXISTS idx_monthlycohorts_cohort_country ON {{ this }} (cohort_country)"
        - "CREATE INDEX IF NOT EXISTS idx_monthlycohorts_customerids ON {{ this }} (customer_ids)"
    dim_customer:
      +post-hook:
        - "CREATE INDEX IF NOT EXISTS idx_customer_customerid ON {{ this }} (customer_id)"
        - "CREATE INDEX IF NOT EXISTS idx_customer_customeridnumeric ON {{ this }} (customer_id_numeric)"
        - "CREATE INDEX IF NOT EXISTS idx_customer_companynameclean ON {{ this }} (company_name_clean)"
        - "CREATE INDEX IF NOT EXISTS idx_customer_contactnameclean ON {{ this }} (contact_name_clean)"
        - "CREATE INDEX IF NOT EXISTS idx_customer_country ON {{ this }} (country)"
    fct_sales:
      +post-hook:
        - "CREATE INDEX IF NOT EXISTS idx_fct_sales_customerid ON {{ this }} (customer_id)"
        - "CREATE INDEX IF NOT EXISTS idx_fct_sales_orderid ON {{ this }} (order_id)"
        - "CREATE INDEX IF NOT EXISTS idx_fct_sales_productid ON {{ this }} (product_id)"

vars:
  "dbt_date:time_zone": "Europe/Berlin"
